name: Go CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Check Formatting
        run: |
          make fmt
          # Fail if make fmt modified any files
          if ! git diff --quiet; then
            echo "Go files are not correctly formatted. Please run 'make fmt'."
            git diff
            exit 1
          fi

      - name: Check Tidy
        run: |
          make tidy
          # Fail if make tidy modified go.mod or go.sum
          if ! git diff --quiet go.mod go.sum; then
            echo "Go modules are not tidy. Please run 'make tidy'."
            git diff go.mod go.sum
            exit 1
          fi

      - name: Test (Production Mode)
        run: make test

      - name: Test (Debug Mode)
        run: make test-debug
